export default {
"login": "MuskanChhatrasal",
"id": 76219453,
"node_id": "MDQ6VXNlcjc2MjE5NDUz",
"avatar_url": "https://avatars.githubusercontent.com/u/76219453?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MuskanChhatrasal",
"html_url": "https://github.com/MuskanChhatrasal",
"followers_url": "https://api.github.com/users/MuskanChhatrasal/followers",
"following_url": "https://api.github.com/users/MuskanChhatrasal/following{/other_user}",
"gists_url": "https://api.github.com/users/MuskanChhatrasal/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MuskanChhatrasal/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MuskanChhatrasal/subscriptions",
"organizations_url": "https://api.github.com/users/MuskanChhatrasal/orgs",
"repos_url": "https://api.github.com/users/MuskanChhatrasal/repos",
"events_url": "https://api.github.com/users/MuskanChhatrasal/events{/privacy}",
"received_events_url": "https://api.github.com/users/MuskanChhatrasal/received_events",
"type": "User",
"site_admin": false,
"name": "Muskan Chhatrasal",
"company": null,
"blog": "",
"location": "Bhopal",
"email": null,
"hireable": null,
"bio": null,
"twitter_username": null,
"public_repos": 16,
"public_gists": 0,
"followers": 16,
"following": 1,
"created_at": "2020-12-18T15:48:13Z",
"updated_at": "2021-08-03T15:05:33Z"
};
